# Generated by Django 5.0.4 on 2024-05-08 11:20

import django.db.models.deletion
import myauth.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myauth', '0002_profile_avatar'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]
