# Generated by Django 5.0.4 on 2024-05-08 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myauth', '0004_appends'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appends',
            name='file',
            field=models.FileField(null=True, upload_to='appends/receipts/'),
        ),
    ]
