# Generated by Django 5.0.4 on 2024-05-11 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myauth', '0008_decision_appends_decision'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_union_member',
            field=models.BooleanField(default=False),
        ),
    ]
