# Generated by Django 5.0.4 on 2024-05-12 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myauth', '0010_appends_commentary_appends_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appends',
            name='commentary',
            field=models.TextField(max_length=1000, null=True),
        ),
    ]
